import { createContext } from 'react';

import type { ProfileContextType } from '@/types/context';

export const ProfileContext = createContext<ProfileContextType>({
  user: null,
  data: null,
  loading: false,
  error: null,
  success: null,
  profileImage: null,
  previewImage: null,
  scores: [],
  scoresCount: 0,
  scoresPage: 1,
  loadingScores: false,
  passwordFormComplete: false,
  setError: () => {},
  setSuccess: () => {},
  handleImageChange: () => {},
  handleUpdateProfile: async () => {},
  setScoresPage: () => {},
  changePassword: () => Promise.resolve(false),
  handleDeleteAccount: async () => {},
  logout: () => {},
  clearState: () => {},
  activeTab: 'overview',
  showPasswordTab: false,
  showDeleteTab: false,
  handleTabChange: () => {},
  handlePasswordClick: () => {},
  handleDeleteClick: () => {},
  setPasswordFormComplete: () => {},
  handleBackToOverview: () => {},
});
